name: Daily SharePoint File Download

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        # Ensure we are in the correct directory for pip install
        # The pip install command should be run from the directory containing requirements.txt
        pip install --upgrade pip
        pip install -r sharepoint_downloader/requirements.txt
    
    - name: Download SharePoint file
      env:
        SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
        SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
        SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
      run: |
        cd sharepoint_downloader
        source ../venv/bin/activate # Activate venv relative to sharepoint_downloader
        python download_sharepoint_file.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Add only if the downloads directory exists and has new files
        if [ -d "sharepoint_downloader/downloads" ] && [ -n "$(ls -A sharepoint_downloader/downloads)" ]; then
          git add sharepoint_downloader/downloads/
          # Check if there are changes to commit to avoid error on no changes
          if ! git diff --staged --quiet; then
            git commit -m "Update SharePoint file" 
            git push
          else
            echo "No changes to commit."
          fi
        else
          echo "Downloads directory is empty or does not exist. No files to commit."
        fi 