name: Update README Date

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  update-date:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.email != 'action@github.com'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update README date
      run: |
        current_date=$(date +"%B %d, %Y")
        sed -i "s/\*\*Last Updated:\*\* .*/\*\*Last Updated:\*\* $current_date/" README.md
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Auto-update README.md date [skip ci]"
        git push origin HEAD:${{ github.ref_name }} 